steps:
  tests:
    image: codeberg.org/freeyourgadget/android-fdroid-tools:33.0.0
    commands:
      - pwd #bump
      - ./gradlew :app:testBangleDebugUnitTest :app:testMainDebugUnitTest

#when:
#repo: Freeyourgadget/Gadgetbridge
#branch: master
#this doesn't work yet:
#https://github.com/woodpecker-ci/woodpecker/issues/687

when:
  # Everything except cron (nightly) and deployment
  - event: push
  - event: pull_request
  - event: tag
  - event: manual
